A start for how to use mongodb and scs as a library
Kyrremann/lastfm-spotify-scrobbler-server pull request #2
Opened 2017-08-04 23:31 UTC by Kyrremann

2017-08-06 15:22 UTC, jeschkies requested changes
Thanks :). I'd rather start now with unit tests for the flask routes than later ;).

2017-08-06 15:22 UTC, jeschkies commented on app.py
> +def test_scrobble():
This should be really part of a unit or integration test ;). Have you written tests in flaks before?

2017-08-07 14:50 UTC, Kyrremann commented on app.py
> +def test_scrobble():
Ah, this was just me testing the code, and I needed a name for my function. The whole route will be removed when I'm done. Sorry for the confusion.

2017-08-13 19:43 UTC, jeschkies requested changes
Pretty good. I'm just wondering if you should go the extra mile an introduce unit tests instead of calling `test_scrobble`. What do you think?

2017-08-13 19:43 UTC, jeschkies commented on app.py
> +    test_scrobble()
Hm, this should not be merged to master :). Maybe a feature branch? Or you add a simple test that runs this method :).

2017-08-17 17:57 UTC, jeschkies requested changes
Thanks a ton. Just a few nitpicking below :).

2017-08-17 17:57 UTC, jeschkies commented on app.py
> +    app.logger.debug(redirect_uri)
Nice!

2017-08-17 17:57 UTC, jeschkies commented on app.py
> +    # return "<a href='{}'>Authenticate Last.fm</a>".format(auth_url)
Can this comment go?

2017-08-17 17:57 UTC, jeschkies commented on templates/index.html
> +<p>Welcome to this simple Spotify to Last.fm scrobble service. What we do is to listen to your last played tracks on Spotify and scrobble them to your Last.fm account. Which makes your scrobbling eas
Cool. Could you warp the text to 80-120 characters? This makes reviewing easier.

2017-08-17 17:57 UTC, jeschkies commented on .gitignore
> +src/
Should this be here?

2017-08-18 07:21 UTC, Kyrremann commented on app.py
> +    # return "<a href='{}'>Authenticate Last.fm</a>".format(auth_url)
Yes!

2017-08-18 07:21 UTC, Kyrremann commented on templates/index.html
> +<p>Welcome to this simple Spotify to Last.fm scrobble service. What we do is to listen to your last played tracks on Spotify and scrobble them to your Last.fm account. Which makes your scrobbling eas
Hehe, sure, didn't thought about that when I was writing the text.

2017-08-18 07:22 UTC, Kyrremann commented on .gitignore
> +src/
I think so. I'm, not that familiar with Python, but it contains a text file called `pip-delete-this-directory.txt`. So I guessed that there was no reason to commit it to the repo.

2017-08-18 20:53 UTC, jeschkies approved these changes
Thanks a ton. I've been too busy this week. I hope to get something done next week.

2017-08-23 21:09 UTC, jeschkies commented
I think you can just merge.

2017-08-24 06:26 UTC, Kyrremann commented
Need to fix one more thing. I haven't tested `task.py` with usernames.

2017-08-24 12:01 UTC, merged